/**
 * ESTA Manufacturer Codes
 *
 * ESTA (Entertainment Services and Technology Association) manufacturer codes
 * used in Art-Net ArtPollReply packets to identify device manufacturers.
 *
 * Format: Array of objects with hex code (with 'h' suffix) as key and manufacturer name as value.
 */

export type ESTAManufacturerCode = Record<string, string>;

// @ts-expect-error - TypeScript union type too complex for large array
export const ESTA_MANUFACTURER_CODES: ESTAManufacturerCode[] = [
    { "0000h": "ESTA" },
    { "0000h": "PLASA" },
    { "0001h": "GEE" },
    { "0002h": "Abstract AVR Ltd." },
    { "0003h": "Chromatech Lighting Co., Ltd." },
    { "0008h": "Guangdong Nanguang Photo & Video Systems Co., Ltd." },
    { "0009h": "Aputure Imaging Industries Co., Ltd." },
    { "000Ah": "Interactive Imagination Ltd." },
    { "000Bh": "Phospec Industries Inc. " },
    { "000Ch": "WAC Lighting Co." },
    { "000Dh": "Guangzhou Haoteng Lighting Co., Ltd." },
    { "000Eh": "Yaoxing Lighting Equipment (Guanghzou）Co., Ltd." },
    { "000Fh": "Shenzhen L-Thinker Technology Co., Ltd." },
    { "0010h": "Dongguan Mi Xing Electronic Technology Co., Ltd." },
    { "0011h": "Beijing Kedeshengye Technology Service Co., Ltd." },
    { "0012h": "Apex Pro Light Co., Ltd." },
    { "0013h": "Litemover BV" },
    { "0014h": "SIRS Electronics, Inc." },
    { "0015h": "Lumencraft Lighting Solutions" },
    { "0016h": "Shenzhen Xuntek Electronics Co., Ltd" },
    { "0017h": "Ereimul" },
    { "0018h": "Macroblock, Inc." },
    { "0019h": "Odelic Co., Ltd." },
    { "001Ah": "DLL Ltd." },
    { "001Bh": "Changsha Sunrise Electronic Technology Co. Ltd." },
    { "001Ch": "Kindwin Technology (HK) Ltd." },
    { "001Dh": "Luminator Technology Group" },
    { "001Eh": "Shenzhen Lumi Lime Technology Limited" },
    { "0020h": "Wattle IT" },
    { "0021h": "Electric Foundry Ltd." },
    { "0022h": "PixelFLEX, LLC" },
    { "0057h": "Blackbezt Lighting Technology Co., Ltd." },
    { "0058h": "Big Dipper Laser Science and Technology Co.,Ltd." },
    { "0059h": "Laysion Lighting Technology Co., Ltd." },
    { "005Ah": "TPD Lighting" },
    { "006Ah": "AIMTECH Electronik Tasarim Ltd. Sti." },
    { "006Bh": "SALZBRENNER media Gmbh" },
    { "006Ch": "Flash-Butrym Sp.J." },
    { "006Dh": "AA Tasarim Ltd." },
    { "006Eh": "WHITEvoid Gmbh" },
    { "006Fh": "AC Power Distribution/ACT Lighting Inc." },
    { "0070h": "Instalighting Gmbh" },
    { "0071h": "Guangzhou Huaxinyuan Electronics Co., Ltd." },
    { "0072h": "Guangzhou Zenith Aurora Lighting Co., Ltd." },
    { "0073h": "Meijay Technologies Co., Ltd." },
    { "0074h": "Thomann Gmbh" },
    { "0075h": "ODELI" },
    { "0076h": "R. S. Schwarze Elektrotechnik Moderne Industrieelektronik Gmbh" },
    { "0077h": "CHAMP Licht" },
    { "0078h": "Andy Lighting Technology Group Ltd." },
    { "0079h": "Leyard Opto Electronics Co., Ltd." },
    { "007Ah": "Equivalent" },
    { "007Bh": "alurays lighting technology Gmbh" },
    { "007Ch": "Huizhou Desay Intelligent Technology Co., Ltd." },
    { "007Dh": "JMS Pro Light" },
    { "007Eh": "Stichting Hypar Collective" },
    { "0080h": "Shenzhen AOTO Electronics Co., Ltd." },
    { "0081h": "Pino Solutions" },
    { "0082h": "LKE Lasershowtechnik Gmbh" },
    { "0083h": "Guangzhou Bright Moon Technology Co., Ltd." },
    { "0084h": "LEDIXIS (Exalux brand)" },
    { "0085h": "Guangzhou Nanshi Light Equipment Co., Ltd." },
    { "0086h": "Intella System Co., Ltd." },
    { "0087h": "LMBD" },
    { "0088h": "Guangzhou YaFeng Optoelectronic Equipment Co., Ltd." },
    { "0089h": "Vulcan Lighting" },
    { "008Ah": "Guangzhou Lees Electronics Co., Ltd." },
    { "008Bh": "Opto Tech Corporation" },
    { "008Ch": "LRX Lighting (Dwight Crane Ltd.)" },
    { "008Dh": "Guangzhou Minghao Electronic Technology Co., Ltd." },
    { "008Eh": "Guangzhou Ao Mei Di Stage Lighting Equipment Co.,Ltd." },
    { "008Fh": "Jiangmen Coolfish Technology Co., Ltd." },
    { "0090h": "Cyclops Lighting" },
    { "0091h": "Guangzhou Shuozhi Optoelectronic Technology Co., Ltd. (Konelite)" },
    { "0092h": "digiLED (UK) Ltd." },
    { "0093h": "Luminous Show Technology Ltd." },
    { "0094h": "Joinmax Display Technology Co., Ltd." },
    { "0095h": "Ningbo Jeg Lighting Tech Co., Ltd." },
    { "0096h": "SiChuan YuZhiWei Information Technology Lt., Co." },
    { "0097h": "AdvancedRay (Beijing) Science & Technology Industries Co., Ltd." },
    { "0098h": "Dedo Weigert Film Gmbh" },
    { "009Ah": "Golden Sea Disco Light Manufacturer" },
    { "009Bh": "Guangzhou Jiawei Electronic Technology Co., Ltd." },
    { "009Ch": "LuxBalance Lighting" },
    { "009Eh": "Guangzhou Flying Butterfly Stage Lighting Equipment Co., Ltd." },
    { "009Fh": "Enedo Power SpA" },
    { "00A0h": "Shenzhen Dicolor Optoelectronics Co., Ltd." },
    { "00A1h": "Creative Lighting And Sound Systems Pty Ltd." },
    { "00A2h": "EMP Designs Ltd." },
    { "00A3h": "GuangZhou Huanshi Lighting Equipment Co., Limited" },
    { "00A4h": "SAKMA Electronica Industrial S.A.U. " },
    { "00A5h": "Delta Electronics, Inc." },
    { "00A6h": "Sensation Lighting Technology Co., Ltd." },
    { "00A7h": "Syncronorm Gmbh" },
    { "00A8h": "Iwasaki Electric Co., Ltd." },
    { "00A9h": "Richter Lighting Technologies GmbH " },
    { "00AAh": "Hangzhou Easun Technology Co., Ltd." },
    { "00ABh": "MFX Asia Co., Ltd" },
    { "00ACh": "ZhouChuang Industrial Co. Limited" },
    { "00ADh": "ColorDeve Co. Limited" },
    { "00AEh": "Vitrulux Ltd" },
    { "00AFh": "NanoPLC LLC" },
    { "00B0h": "ARENA LUCI s.r.l." },
    { "00B1h": "Guangzhou Omarte Lighting Co., Ltd." },
    { "00B2h": "unonovesette srl" },
    { "00B3h": "LANTERN" },
    { "00B4h": "Lumos Design" },
    { "00B5h": "Suga koubou Co., Ltd." },
    { "00B6h": "DiGidot Technologies BV" },
    { "00B7h": "Bron Elektronik AG" },
    { "00B8h": "Shenzhen Singba Light Technology Co., Ltd." },
    { "00B9h": "Guangzhou Baiyun District Sanjie Eletronic Stage Lighting Audio Equipment Factory" },
    { "00BAh": "LiteGear Inc." },
    { "00BBh": "Digital Lighting Engineering & Design, LLC" },
    { "00BCh": "Ambion GmbH (Ambrain)" },
    { "00BDh": "numeo Gmbh" },
    { "00BEh": "The Light Luminary for Cine and TV S.L. (VELVET LIGHT) " },
    { "00BFh": "LumiOS (GTR Industries)" },
    { "00C0h": "Foshan Yinhe Lanjing Lighting & Electrical Co., Ltd." },
    { "00C1h": "Jingchuang Water Technology" },
    { "00C2h": "Ledogen" },
    { "00C3h": "Xicato" },
    { "00C4h": "Guangzhou Dahe Electronic Technology Co. Ltd." },
    { "00C5h": "DAGE Stage Lighting Master Co., Ltd." },
    { "00C6h": "Guangzhou Lantian Electronic Technology Co., Ltd." },
    { "00C7h": "THOR" },
    { "00C8h": "Constell8 NV" },
    { "00C9h": "Pangaea Technology" },
    { "0101h": "St. Anne Engineering Gmbh" },
    { "0102h": "Bortis Elektronik" },
    { "0103h": "Fontana Technologies" },
    { "0104h": "Blizzard Lighting, LLC" },
    { "0105h": "LIGHTHOW (SHANGHAI) Ltd." },
    { "0106h": "A.L.A. Equipment Company Ltd." },
    { "0107h": "Inventronics (Hangzhou), Inc." },
    { "0108h": "Haya Lighting Equipment Limited" },
    { "0109h": "V-Productions" },
    { "010Ah": "Elektralite" },
    { "010Bh": "DesignLED Technology (HK) Co., Ltd." },
    { "010Ch": "SES (Entertainment Services) Ltd." },
    { "010Dh": "Lumos / DMLite" },
    { "010Eh": "Guangzhou ATON Lighting Technology Co.,Ltd" },
    { "010Fh": "Saco Technologies Inc." },
    { "0110h": "APF S.r.l." },
    { "0111h": "Radig Hard & Software" },
    { "0112h": "RGB Lighting Equipment Co., Ltd." },
    { "0113h": "Airstar SAS" },
    { "0114h": "BSL Lighting" },
    { "0115h": "Kontrolcla Show Control S.L." },
    { "0116h": "SmoothLUX B.V." },
    { "0117h": "AD Toyo Lighting (Guangzhou) Co.,Ltd" },
    { "0118h": "Vello Light Co., Ltd." },
    { "0119h": "Peter Schneyder Design Management Gmbh" },
    { "011Ah": "Guangzhou Hotion Technology Co., Ltd." },
    { "011Bh": "Jumptronic Gmbh" },
    { "011Ch": "Letong Electronic (Guangzhou) Co., Ltd." },
    { "011Dh": "Yangzhou Zhituo Lighting Vision Technology Co., Ltd. " },
    { "011Eh": "Master LED" },
    { "011Fh": "STF s.r.l." },
    { "0144h": "KW-Veranstaltungstechnik" },
    { "016Ch": "LGR" },
    { "016Dh": "Hive Lighting" },
    { "016Eh": "Artled Technology Corp." },
    { "016Fh": "SQD Lighting Co. Ltd " },
    { "018Fh": "Guangzhou YiCheng Light Industry Ltd." },
    { "0190h": "Wizlogics Co., Ltd." },
    { "0191h": "Sycra Technologies" },
    { "0192h": "Metro Marine LLC" },
    { "0193h": "DMF Lighting" },
    { "0199h": "Ocean LED Marine Ltd." },
    { "019Ah": "TwoGain Electronics" },
    { "019Bh": "ElectroTAS Soluciones Profesionales" },
    { "019Ch": "Ningbo Snappy Optoelectronics Co., Ltd." },
    { "019Fh": "DaisaLed Ltd." },
    { "01A0h": "Light With LED" },
    { "01A1h": "Yuesheng Stage Light Limited" },
    { "01A2h": "Art Lighting Production, s.r.o." },
    { "01A3h": "Dongguan Yongya Technology Co., Ltd" },
    { "01A4h": "Custom Effects LED Solutions Inc." },
    { "01A5h": "MJ Lighting Co., Ltd." },
    { "01A6h": "Hengmei Lighting Technology Co., Ltd." },
    { "01A8h": "ZongDa Photoelectricity Science and Technology Co., Ltd." },
    { "01A9h": "Shenzhen Uniview LED Ltd. Co." },
    { "01AAh": "Videndum Production Solutions Inc." },
    { "01ABh": "Shanghai Euchips Industrial Co., Ltd." },
    { "01ACh": "DongGuan Phcistar Optoelectronics Technology Co., Ltd." },
    { "01AFh": "Hunan Minghe Opto Tech Co., Ltd." },
    { "01B1h": "Lightcare A/S" },
    { "01B2h": "DJSI Schinstad ANS (Northern Light)" },
    { "01B3h": "Ricardo Dias" },
    { "01B4h": "Inventeq B.V." },
    { "01B5h": "Beijing Soft Rock Technology Development Co., Ltd." },
    { "01BEh": "BEN-RI Electronica S.A." },
    { "01C7h": "SCHIEDERWERK GmbH " },
    { "01C8h": "Guangzhou JINLIN Stage Lighting Equipment Co., Ltd. " },
    { "01C9h": "ALPHA LITE Inc." },
    { "01CAh": "CASCADE s.a.s." },
    { "01CBh": "ILT Italy SRL" },
    { "01CCh": "Portman Custom Lights" },
    { "01CDh": "Compulite Systems (2000) LTD" },
    { "01CEh": "Railiks Enterprises" },
    { "01CFh": "SRM Technik Gmbh" },
    { "01D0h": "Shanghai Semping Electronics Co., Ltd." },
    { "01D1h": "Yarilo Pro" },
    { "01D2h": "GIP Innovation Tools Gmbh" },
    { "01D3h": "JSC Aksera" },
    { "01D4h": "x-labs" },
    { "01D5h": "Shenzhen Liantronics Co., Ltd" },
    { "01D6h": "Argent Data Systems, Inc." },
    { "01D7h": "LIMEDIA" },
    { "01D8h": "Daniel Large Lighting" },
    { "01D9h": "Lightronics Inc." },
    { "01DAh": "Guangzhou Daisy Electronic Technology Co., Ltd. " },
    { "01DBh": "Logen Ltd." },
    { "01DCh": "LED Linear Gmbh" },
    { "01DDh": "Photonia srl" },
    { "01DEh": "Guangzhou Baiyun Xinxiang Lighting Equipment Factory (XPRO LIGHT)" },
    { "01DFh": "GuangZhou Dream Lighting Equipment Co., Ltd." },
    { "01E0h": "IBN Labs Ltd." },
    { "0200h": "Lighting Infusion LLC" },
    { "0201h": "Blinkinlabs, LLC " },
    { "0202h": "Paul Heuts" },
    { "0203h": "Artemide S.p.A" },
    { "0204h": "LIGHTLINE Lasertechnik Gmbh" },
    { "0205h": "SmartShow UK" },
    { "0206h": "Studio Due Light S.r.l." },
    { "0207h": "SILL LIGHTS Gmbh" },
    { "0208h": "Shenzhen Yuming Vision Technology Co., Ltd." },
    { "0209h": "ER Productions" },
    { "020Ah": "Seebacher Gmbh" },
    { "0210h": "Leksa Lighting Technologies Pvt. Ltd." },
    { "0211h": "Arkaos S.A." },
    { "0212h": "Frame The Space (FTSLED)" },
    { "0213h": "Huizhou visionX Technology Co., Ltd." },
    { "0214h": "Impactrum" },
    { "021Ah": "WizzuLED by Scooon" },
    { "0223h": "ShenZhen Focus Vision Intelligent System Co., Ltd." },
    { "0224h": "Vanguard LED Displays" },
    { "0225h": "Northern Lights Electronic Design, LLC" },
    { "0235h": "Company 235, LLC" },
    { "0242h": "ABLELITE INTERNATIONAL" },
    { "024Ch": "FBFX Ltd" },
    { "025Bh": "Imlight-Showtechnic" },
    { "026Fh": "Acuity Brands Lighting Inc." },
    { "0280h": "Arrigo Lighting" },
    { "0286h": "RMLX" },
    { "028Fh": "GRE Alpha Electronics Ltd." },
    { "02A0h": "LLC Likhoslavl Plant of Lighting Engineering (Svetotehnika)" },
    { "02A1h": "LLC Moscow Experimental Lighting Plant (TeleMechanic)" },
    { "02A2h": "OJSC Kadoshkinsky electrotechnical " },
    { "02A3h": "Big Bang Lightning" },
    { "02A4h": "McNicoll Entertainment Systems" },
    { "02AAh": "Jinnax Opto Technology Co., Ltd. " },
    { "02ABh": "Rift Labs" },
    { "02ACh": "PSL Electronik Sanayi ve Ticaret A.S." },
    { "02ADh": "SAVI Controls LLC" },
    { "02AEh": "Tea Engineering Ltd." },
    { "02AFh": "JMAZ Group, Inc." },
    { "02B0h": "DMXControl-Projects e.V." },
    { "02B1h": "Global Design Solutions Korea" },
    { "02B2h": "Guangzhou Harbinger Co., Ltd." },
    { "02BAh": "Chainzone Technology (Foshan) Co., Ltd." },
    { "02BCh": "PXP Technology" },
    { "02BDh": "RE-Engineering" },
    { "02C8h": "Growflux LLC" },
    { "02C9h": "Theatrixx Technologies" },
    { "02CAh": "Acclaim Lighting" },
    { "02CBh": "GVA Lighting, Inc." },
    { "02CCh": "Brightix" },
    { "02D0h": "Winona Lighting" },
    { "02D1h": "Hoffmeister Leuchten Gmbh" },
    { "02E1h": "Tait Towers Manufacturing Inc." },
    { "02E2h": "CLF Lighting BV." },
    { "02EAh": "d3 Technologies Ltd." },
    { "02EBh": "Amolvin Research & Development Lab." },
    { "02ECh": "Lutron Electronics" },
    { "02EDh": "OpenLX SP Ltd." },
    { "02EEh": "Firma GUTKOWSKI - Gutkowski Jan" },
    { "02EFh": "ABLETECH Co., Ltd." },
    { "02F0h": "iColor LED Shenzhen Co., Ltd." },
    { "02F1h": "Lichtmanufaktur Berlin Gmbh" },
    { "02FFh": "Guangzhou Eway Stage Equipment Technology Co., Ltd." },
    { "0302h": "Swefog Technology Group AB" },
    { "0303h": "Shanghai Moons' Automation Control Co., Ltd" },
    { "0305h": "DiCon Fiberoptics, Inc." },
    { "0306h": "feno Gmbh" },
    { "0307h": "Ledium Kft." },
    { "0308h": "ImageCue LLC " },
    { "030Ah": "Shenzhen Colordreamer Tech Ltd." },
    { "030Bh": "Guangzhou Wanrui Stage Light Equipment Co., Ltd." },
    { "030Fh": "EK INC (formerly Guangzhou Litewise Lighting Equipments Co., Ltd.)" },
    { "0311h": "Guangzhou PUGUANG Electronic Technology Co., Ltd." },
    { "0312h": "Guangzhou Xingkong Studio Lighting Co., Ltd." },
    { "032Ch": "Carallon Ltd." },
    { "033Ah": "Lux Lumen" },
    { "034Bh": "Rosstech Signals Inc." },
    { "0378h": "KASUGA" },
    { "038Fh": "Strich Labs" },
    { "0391h": "Alcorn McBride Inc." },
    { "0393h": "i2Systems" },
    { "0394h": "Prism Projection" },
    { "039Bh": "Lightforce Lasertechnik" },
    { "03A1h": "INAREX INC." },
    { "03A2h": "licht.team" },
    { "03A8h": "ARTFOX" },
    { "03AAh": "AIGA Electronic (GuangZhou) Co., Ltd." },
    { "03ABh": "ABMICROLONDON" },
    { "03C6h": "NYSOFT" },
    { "03CEh": "MVI LLC" },
    { "03D5h": "eX Systems" },
    { "03D6h": "i-Lumen" },
    { "03DAh": "QST LED" },
    { "03E8h": "Acson" },
    { "03F0h": "jpbaye.de" },
    { "03FAh": "ART-DMX" },
    { "0402h": "Exato" },
    { "0404h": "Luminxa" },
    { "040Eh": "Optoma Corporation" },
    { "0411h": "SoundSwitch" },
    { "0412h": "D's DMX" },
    { "041Ch": "IMLIGHT" },
    { "0424h": "FLUX ECLAIRAGE" },
    { "0428h": "ITSTECh" },
    { "0430h": "BOE MLED Technology Co., Ltd" },
    { "043Ch": "Volux Lighting" },
    { "0440h": "Guangzhou VAS Lighting Co., Ltd." },
    { "044Eh": "Ben Peoples Industries, LLC" },
    { "044Fh": "B2 Co., Ltd." },
    { "0455h": "Lamp & Pencil" },
    { "047Ch": "LedsGo" },
    { "0480h": "ASUSTeK Computer Inc." },
    { "0486h": "LANZ (CZ) Lighting Ltd" },
    { "048Eh": "Krisledz Pte. Ltd." },
    { "048Fh": "Grand Canyon LED Lighting System (Suzhou) Co., Ltd. " },
    { "04A6h": "MEB Veranstaltungstechnik Gmbh" },
    { "04A9h": "Edward J. Keefe Jr." },
    { "04B2h": "Shenzhen Meiyad Optoelectronics Co., Ltd" },
    { "04B4h": "SKT Inc." },
    { "04B5h": "Major" },
    { "04B6h": "IntiLED" },
    { "04B8h": "Guangzhou Hongcai Stage Equipment Co., Ltd." },
    { "04C4h": "Ephesus Lighting, Inc." },
    { "04CAh": "RT-DMX" },
    { "04CCh": "Yubang Ruiying (Zhongshan) Electronics Co., LTD" },
    { "04CEh": "Quisda" },
    { "04D6h": "Kessil" },
    { "04D7h": "Targetti Sankey Spa" },
    { "04D8h": "Guangzhou Hong Yuan Electronic Technology Co., LTD." },
    { "04DCh": "Modern Stage Service Projects" },
    { "04DDh": "Topstriving Photoelectricity Technology Co., Ltd." },
    { "04E6h": "Kelvix" },
    { "04EEh": "Tivoli Lighting" },
    { "04F0h": "SIGMA NET" },
    { "04F4h": "Zeraus" },
    { "04FCh": "Syncrolite LLC" },
    { "0504h": "MYHP Limited" },
    { "050Ah": "ChamSys Ltd." },
    { "051Ch": "Ambitsel, Inc." },
    { "0520h": "ANLC Ltd" },
    { "0529h": "OSRAM" },
    { "052Ah": "DELTACAST" },
    { "0536h": "tarm AG" },
    { "0537h": "TERMINAL-COM" },
    { "0540h": "EverBrighten Co., Ltd." },
    { "0555h": "Maresch Electronics" },
    { "0556h": "RAYSYS" },
    { "055Fh": "PRO-SOLUTIONS" },
    { "056Bh": "COSMOLIGHT SRL" },
    { "056Ch": "Lumascape Lighting Industries" },
    { "0573h": "JIAXING XINHUALI LIGHTING & SOUNDING CO., LTD." },
    { "057Ah": "RVE S.A.S." },
    { "0580h": "Innovation LED Limited" },
    { "0582h": "Jack LINE" },
    { "0586h": "K 5600, Inc." },
    { "0588h": "GuangZhou XiangMing Light Limited " },
    { "0592h": "MIRAGE B.V." },
    { "0596h": "ReveLux" },
    { "05A0h": "Stage Smarts AB" },
    { "05A4h": "IMMOLAS" },
    { "05A8h": "Owl Labs" },
    { "05ABh": "Shenzhen Lesan Lighting Co., Ltd. " },
    { "05B5h": "Turkowski GmbH " },
    { "05BCh": "CantoUSA" },
    { "05C0h": "Vertigo" },
    { "05CFh": "Brighten Technology Development Co., Ltd." },
    { "05D3h": "D-LED Illumination Technologies Ltd." },
    { "05DAh": "Spacyal" },
    { "05E0h": "esp_dmx" },
    { "05E2h": "KORRO PLUS" },
    { "05E8h": "Snap One" },
    { "05EBh": "GUANGZHOU BO WEI TE LIGHTING CO.LTD" },
    { "05EFh": "Guangzhou Chai Yi Light Co., Ltd." },
    { "05F2h": "O'Light" },
    { "05F6h": "Otiru Oy" },
    { "05F7h": "Immersive Design Studios Inc. " },
    { "0600h": "TELMIC Neo" },
    { "0602h": "Guangzhou Jinhong Stage Lighting Equipment.Co.,ltd" },
    { "0606h": "Guangzhou YiGuang Stage Lighting Co., Ltd." },
    { "0609h": "Diginet Control Systems Pty Ltd" },
    { "060Ah": "Kindwin Opto Electronic (ShenZhen) Co. Ltd" },
    { "060Bh": "Lighting Science Group (formerly LED Effects, Inc.)" },
    { "060Dh": "HANIL TNC CO.,LTD" },
    { "061Ch": "LEDRAYS INC" },
    { "0622h": "Lupo SRL" },
    { "0623h": "JAS LIGHTING & SOUND CO., LTD." },
    { "0624h": "S4 Lights" },
    { "0628h": "ERP Power" },
    { "062Ah": "LEDstructures " },
    { "062Bh": "CKC Lighting Co., Ltd." },
    { "063Ah": "AVM Belgium BVBA" },
    { "063Ch": "LaserNet" },
    { "0644h": "COLEDER DISPLAY CO., LTD." },
    { "0645h": "MATSUMURA ELECTRIC MFG. CO. , LTD." },
    { "064Dh": "KXD LIGHTING CO., LIMITED" },
    { "064Eh": "My Method" },
    { "0650h": "RDC, Inc. d.b.a. LynTec" },
    { "0653h": "USAI, LLC" },
    { "0654h": "HUNAN XIANG CAIXU FILM AND TELEVISION CULTURE CO.LTD" },
    { "0658h": "AZCOLOR LITE CO., LIMITED" },
    { "065Eh": "OFilms" },
    { "0660h": "QSTECH CO.,LTD" },
    { "0668h": "Motion FX" },
    { "066Bh": "AVANT-GARDE DE STUDIO FZ LLC" },
    { "066Fh": "GUANGZHOU CY LIGHTING EQUIPMENT CO.,LTD" },
    { "0674h": "Raylogic Control systems Pvt Ltd." },
    { "067Ah": "Inster Co, Ltd" },
    { "067Ch": "LOTRONIC SA" },
    { "0682h": "Beijing Ming Rui Lighting Technology Co., Ltd. " },
    { "0684h": "LEDART LLC" },
    { "0685h": "IBL/ESD-Datentechnik Gmbh" },
    { "0687h": "INSMARINE LLC" },
    { "0688h": "LUCIDISCENA" },
    { "0689h": "GUANGDONG DONE POWER TECHNOLOGY CO" },
    { "068Ch": "Hitmusic SAS" },
    { "068Eh": "GUANGZHOU TEANMA STAGE LIGHTING FACTORY" },
    { "068Fh": "LEDEC GROUP LIMITED" },
    { "0692h": "TORO SYSTEM" },
    { "0696h": "SHENZHEN HOION LIGHTING CO.,LTD" },
    { "0697h": "Shenzhen LED Innovator Technology Co., Ltd" },
    { "0698h": "Techni-Lux" },
    { "06A0h": "Light.Audio.Design" },
    { "06A1h": "ProTec Gmbh" },
    { "06A3h": "RODLIGHT ALBRECHT SILBERBERGER" },
    { "06ACh": "GOLVER PROJECTS S.L." },
    { "06ADh": "LEDMAN OPTOELECTRONIC CO.,LTD." },
    { "06AEh": "CANARA LIGHTING INDUSTRIES PVT LTD" },
    { "06AFh": "ZHEJIANG JINGRI TECHNOLOGY CO.,LTD" },
    { "06B3h": "NANOLUMENS, INC." },
    { "06B6h": "GUANGDONG VSHINE LIGHTING TECHNOLOGY CO.,LTD" },
    { "06B9h": "GUANGZHOU DASEN LIGHTING CORPORATION LIMITED" },
    { "06BBh": "IQ COMPANY Ltd." },
    { "06C4h": "RHENAC Systems Gmbh" },
    { "06C5h": "ZHIYUN INFORMATION (INTERNATIONAL) TECHNOLOGY CO., LIMITED" },
    { "06C7h": "L&L Luce&Light" },
    { "06CAh": "Leding" },
    { "06CEh": "American-Pro International" },
    { "06D1h": "BIRUN ELECTRONIC INDUSTRIAL CO., LTD" },
    { "06D2h": "LIGHTSTAR (BEIJING) ELECTRONIC CORPORATION" },
    { "06D3h": "Boerner Distribution International Gmbh" },
    { "06DDh": "GRUPPO SIGI SRLS" },
    { "06E0h": "SHENZHEN LONGRUN OPTOELECTRONIC CO., LTD" },
    { "06E1h": "Burck IT GmbH & Co. KG" },
    { "06E2h": "ScreenCo" },
    { "06E4h": "Dydell B.V." },
    { "06E6h": "Equipson S.A." },
    { "06ECh": "SISTEMA Jsc" },
    { "06F0h": "CTG sp. z o.o." },
    { "06F1h": "Aqualux Lighting" },
    { "06F8h": "CHONGQING XINYUANHUI OPTOELECTRONIC TECHNOLOGY CO.,LTD" },
    { "0700h": "OXYGEN SMD Ltd" },
    { "0702h": "Drinelec" },
    { "0706h": "LINEAR TECHNOLOGIE" },
    { "0707h": "Conceptinetics Technologies and Consultancy Ltd." },
    { "0708h": "AK-LIGHT" },
    { "070Ch": "Pixout SIA" },
    { "070Dh": "Lumenwerx ULC" },
    { "070Eh": "PragmaLab" },
    { "070Fh": "Theatrelight New Zealand" },
    { "0710h": "D.T.S. Illuminazione srl" },
    { "0711h": "Halonix Technologies Pvt Ltd." },
    { "0712h": "Laser Imagineering Gmbh" },
    { "0716h": "Artem Ltd. " },
    { "0718h": "Eagle Lite" },
    { "071Ah": "YHX Visual" },
    { "071Fh": "Moss LED Inc" },
    { "0724h": "PHC Lighting & BMS Sp. z o.o." },
    { "072Bh": "NEWSUBSTANCE Ltd. " },
    { "072Ch": "SGM A/S" },
    { "072Dh": "Sting Alleman" },
    { "072Fh": "RayComposer - R. Adams" },
    { "0732h": "Galaxia Electronics" },
    { "0734h": "CPOINT" },
    { "073Ah": "AML Lighting Co.,LTD" },
    { "073Bh": "Corsair Technology Ltd." },
    { "0740h": "Arkalumen" },
    { "0744h": "DMX Pro Sales, LLC" },
    { "0745h": "Guangzhou Wingo Stage Light Co., Ltd" },
    { "0748h": "Chromateq" },
    { "074Fh": "Panasonic Corporation" },
    { "0753h": "F&V Europe B.V." },
    { "0758h": "IMPOLUX Gmbh" },
    { "075Fh": "LEDEngin Inc." },
    { "076Ah": "BeamZ (Tronios B.V.)" },
    { "076Eh": "DecoLed, LLC" },
    { "0776h": "lumenetix" },
    { "077Bh": "GENLED Brands" },
    { "0782h": "R9 Lighting" },
    { "0786h": "DMXDesktop" },
    { "078Ah": "FATEC sarl" },
    { "078Eh": "SHENZHEN BGLOPTO TECHNOLOGY Co., LTD." },
    { "0792h": "MY-Semi Inc." },
    { "0797h": "ARCPROLED Limited" },
    { "079Bh": "Pro Church Lights" },
    { "079Fh": "VPS Group, LLC" },
    { "07A3h": "Guangzhou GBR PROLIGHT GROUP CO.,LTD (GBR PROLIGHT)" },
    { "07A5h": "X LED Systems" },
    { "07ADh": "CLS LED BV" },
    { "07AEh": "A-LITE B.V." },
    { "07B0h": "ADDiCTiON BoX GbR" },
    { "07B1h": "TBF-PyroTec GmbH " },
    { "07B3h": "Shenzhen Fabulux Technology Co., Ltd" },
    { "07B5h": "ARM Automation, Inc" },
    { "07B6h": "Minleon USA" },
    { "07B8h": "Zhuhai Demi Technology Co., Ltd." },
    { "07BAh": "Tradia Co., LTD" },
    { "07BBh": "Shenzhen SOSEN Electronics Co., Ltd." },
    { "07BEh": "Sanko Device Co.Ltd." },
    { "07C0h": "Code Mercenaries Gmbh" },
    { "07C2h": "BOOQlight BV" },
    { "07C5h": "SBS Lighting LLC" },
    { "07C6h": "BK Lighting" },
    { "07C8h": "Sidus Link Ltd." },
    { "07CCh": "Griven S.r.l." },
    { "07CFh": "MH-Sound" },
    { "07D1h": "Made By Mouse LTD" },
    { "07D2h": "Guangdong The One Studio Co., Limited" },
    { "07D5h": "PHIDA Stage Equipment Co., Ltd" },
    { "07D6h": "Lite Puter Enterprise Co., Ltd." },
    { "07DAh": "Flytech s.r.l." },
    { "07DCh": "EVLight (Guangzhou) Co.,Ltd." },
    { "07E8h": "ROCKETSIGN Technology HK Ltd" },
    { "07E9h": "TechLink Co., Ltd." },
    { "07EAh": "Le Maitre Ltd" },
    { "07EFh": "Guangzhou V-Show Pro Lighting Co., Ltd." },
    { "07F0h": "Lifud Technology Co., Ltd" },
    { "07F2h": "CB Electronics" },
    { "07F3h": "Sam Light" },
    { "07F4h": "LED Flex Ltd." },
    { "07F5h": "Shenzhen ATENTI Technologies Co., Ltd" },
    { "07F6h": "Electric Distribution Systems" },
    { "07F7h": "Dakco Technologies Co., Ltd." },
    { "07F8h": "Ultimate Technology Solutions Gmbh" },
    { "07F9h": "Bion Technologies Gmbh" },
    { "07FAh": "Shenzhen Pony Systems Tech Co., Ltd." },
    { "07FCh": "Electro Mind Co., Ltd." },
    { "07FDh": "THELIGHT Luminary for Cine and TV S.L." },
    { "07FEh": "Shenzhen Apexls Optoelectronic Co., Ltd." },
    { "07FFh": "Guangzhou HOMEI LIGHT Manufacturer" },
    { "0800h": "Hongyeah Light" },
    { "0801h": "Guangzhou Favolite Stage Lighting Co., Ltd." },
    { "0802h": "AstralPool" },
    { "0803h": "Guangzhou FutureColor Electronic Technology Co., Ltd. " },
    { "0804h": "K&G Visual Technology" },
    { "0805h": "T.C.M. Light-Solutions" },
    { "0806h": "Air Giants Limited" },
    { "0807h": "Event Lighting Pty, Ltd." },
    { "0808h": "Cooper Lighting - Zero 88" },
    { "0809h": "mumoco Gmbh" },
    { "080Ah": "Shenzhen FantaLED Electronics Co., Ltd" },
    { "080Dh": "HBJ Elektronik" },
    { "080Fh": "NavoLabs" },
    { "0810h": "BDS Studios" },
    { "0811h": "V-PRO" },
    { "0812h": "Yamagiwa Corporation" },
    { "0813h": "Shenzhen Scenico Optoelectronic Co., Ltd." },
    { "0814h": "squareV" },
    { "0816h": "Benjamin Graf Ton- und Medientechnik" },
    { "081Ch": "MR Electronics Ltd." },
    { "081Eh": "LOBO Electronic Gmbh" },
    { "0822h": "Hangzhou YD Illumination Co., Ltd" },
    { "0823h": "Opito Labs Gmbh" },
    { "0824h": "Almotechnos CO.,LTD." },
    { "0827h": "PIXREAL" },
    { "0829h": "CR-TEC Photoelectric" },
    { "0832h": "Shenzhen EXC-LED Technology Co.,Ltd" },
    { "0836h": "Nyvoll Lys" },
    { "0838h": "LaserAV" },
    { "083Ah": "Bright Ideas Custom Electronics Inc." },
    { "083Ch": "TDT Productions" },
    { "083Eh": "Guangdong Hua Chen Film & Television Stage Project Co., Ltd." },
    { "083Fh": "Shenzhen LeiFei Lighting Technologies Co.,Ltd." },
    { "0840h": "Shenzhen Zwich Science and Technology Co.Ltd." },
    { "0841h": "Guangzhou ICON Lighting Co.,Ltd" },
    { "0843h": "BHL Lichttechniek" },
    { "0845h": "Cush Light LLC" },
    { "0846h": "LDR - Luci della Ribalta Srl" },
    { "0848h": "SLC - Static Light Company Ltd" },
    { "084Bh": "Neon Circus Ltd" },
    { "084Ch": "Guangzhou Ba Lin Electronic Technology Co., Ltd." },
    { "084Dh": "Guangzhou NECO Stage Lighting Factory" },
    { "084Eh": "RGBshine Technology Co. Ltd." },
    { "084Fh": "Mantic Lighting Co.,Ltd" },
    { "0850h": "Proland Group, LLC" },
    { "0851h": "Junction Inc. Ltd" },
    { "0854h": "NEC Display Solutions, Ltd." },
    { "0854h": "Sharp NEC Display Solutions, Ltd." },
    { "0855h": "GODOX Photo Equipment Co., Ltd." },
    { "0856h": "Ctrl Element ehf" },
    { "0858h": "Juno Lighting Group " },
    { "085Ah": "Guangzhou Ming Jing Stage Light Equipment Co., Ltd." },
    { "085Bh": "Tolifo (Dongguan) Photographic Equipment Co. Ltd" },
    { "085Eh": "MMS Distribution Ltd" },
    { "085Fh": "Media Visions, Inc." },
    { "0862h": "illuminous" },
    { "0863h": "XTEC Industries Pte Ltd" },
    { "0864h": "Hangzhou Youte Power., Co. Ltd" },
    { "0865h": "Contrade Gmbh" },
    { "0866h": "PAL Lighting" },
    { "0867h": "Huizhou LATU Film Equipment Co., Ltd" },
    { "0868h": "Ushio America, Inc." },
    { "0869h": "Club Cannon LLC" },
    { "086Ah": "Shenzhen Chip Optech Co.,LTD" },
    { "086Ch": "Bafa Elektronik ve Işık Tasarımları Sanayii Ticaret LTD Sti." },
    { "086Dh": "Velaflame, LLC" },
    { "086Eh": "Guangzhou Hi-LTTE Electronics Technology Co.,Ltd " },
    { "086Fh": "MARTINI RUS LLC" },
    { "0870h": "Hunan YESTECH Optoelectronic Co., Ltd" },
    { "0871h": "Changsha Maya Special Effects Equipment Co., Ltd" },
    { "0873h": "Guangzhou BKLite Stage Lighting Equipment Co.,LTD" },
    { "0874h": "Snow Professional Lighting" },
    { "0875h": "ARC Solid-State Lighting Corp." },
    { "0876h": "Power Gems LTD" },
    { "0877h": "Skaff New Zealand Ltd" },
    { "0878h": "OTTEC Technology Gmbh" },
    { "087Ah": "Dextra Group Plc" },
    { "087Bh": "About Time Technologies" },
    { "087Ch": "Telectran International Pty Ltd." },
    { "087Dh": "TPV Technology Group" },
    { "0880h": "GuangZhou LiDang Technology Inc." },
    { "0881h": "Shenzhen Genesis-Systech Co., Ltd." },
    { "0883h": "CEE Lighting Equipment Co.Ltd" },
    { "0884h": "Bright Group" },
    { "0885h": "SIRS-E" },
    { "0886h": "KLIK Systems" },
    { "0887h": "PrimOtek s.r.l.s." },
    { "0888h": "Banglux Lighting Technology Co., Ltd." },
    { "0889h": "Guangzhou Shenghui Electronic Technology Co., Ltd" },
    { "088Ah": "Highendled Electronics Company Limited" },
    { "088Bh": "Shenzhen Doit Vision Co., Ltd" },
    { "088Ch": "Guangzhou Yi Sheng Yuan Electronic Co.,Ltd(Esun)" },
    { "088Dh": "Guangzhou Ling Yang lighting Science and Technology Co.,Ltd" },
    { "088Eh": "Stage One International Co., Ltd. " },
    { "088Fh": "First Design System Inc." },
    { "0890h": "Taurus Light Co.,Limited" },
    { "0891h": "Feiner Lichttechnik GMBh" },
    { "0892h": "DongGuan Ruishen Technology Co.,Ltd" },
    { "0893h": "Brighten LED Lighting Limited" },
    { "0894h": "Dongguan HCP Technology Co., Ltd." },
    { "0896h": "CSD Design and Fabrication" },
    { "0899h": "Shenzhen Huimont Technology Co., Ltd" },
    { "089Ah": "ADL Electronics Ltd." },
    { "089Dh": "gobo.ws" },
    { "08A1h": "Shenzhen Gloshine Technology Co., Ltd" },
    { "08A2h": "Guangzhou Gesida Light Equipment Co., Ltd." },
    { "08A3h": "Redot Visual Effect Technologies (Shenzhen) Co., Ltd" },
    { "08A4h": "Adam Hall Gmbh" },
    { "08A5h": "White Wing Logic" },
    { "08A6h": "impulswerk.de" },
    { "08A7h": "GuangZhou Deliya Opto-electronic Tech Co., Ltd" },
    { "08A8h": "Guangzhou Yunpeng Lighting Equipment Co. Ltd." },
    { "08A9h": "Lighten Corp." },
    { "08AAh": "PiXL Factory" },
    { "08ABh": "Qdot Lighting Limited " },
    { "08ACh": "Bushveld Labs" },
    { "08ADh": "Optical Productions LLC" },
    { "08AEh": "Technical Audio Group Pty Ltd" },
    { "08AFh": "AAdyn Technology" },
    { "08B0h": "KIM Lighting" },
    { "08B1h": "Fujian Starnet Evideo Information System Co.,Ltd." },
    { "08B2h": "MCI Group" },
    { "08B3h": "Stealth Light srl" },
    { "08B4h": "Ledera Technology Co.,Ltd" },
    { "08B5h": "ShenZhen Sunny Xiao Technology Co., Ltd." },
    { "08B6h": "Graf Lichttechnik UG" },
    { "08B8h": "LEDScape Lighting" },
    { "08B9h": "Guangzhou Hua Rong Electronic Technology Co., Ltd." },
    { "08BAh": "Meteor Lighting" },
    { "08BBh": "Guangzhou CHEN Electronic Technology Co., Ltd." },
    { "08BCh": "Michael Parkin" },
    { "08BDh": "Lug Light Factory Sp. z o. o." },
    { "08BEh": "Shenzhen FloatStone Technology Co., Ltd. " },
    { "08BFh": "Times Square Stage Lighting Inc." },
    { "08C0h": "Real Tech International LTD." },
    { "08C1h": "Project SSSHH Incorporated" },
    { "08C2h": "Guangzhou Huipu Stage Effect Equipment Co., Ltd" },
    { "08C3h": "Guangzhou Spark Stage Equipment Co. Ltd" },
    { "08C4h": "Jacek Wagner" },
    { "08C5h": "EHRGEIZ Lichttechnik Gmbh" },
    { "08C6h": "Guangzhou Ever Famous Electronic Co.,Ltd" },
    { "08C7h": "Shenzhen SOSTRON Technology Co., Ltd" },
    { "08C9h": "LEDitgo Videowall Germany Gmbh" },
    { "08CAh": "Foshan City Xuandao Optoelectronics Equipment Co., Ltd" },
    { "08CBh": "Practical LEDs.com" },
    { "08CCh": "Guangzhou Santu Stage Lighting Equipment Co.Ltd" },
    { "08CEh": "Zhejiang DGX Electronic Technology Co.,Ltd" },
    { "08D0h": "Image Engineering" },
    { "08D1h": "Shenzhen Leqi Network Technology Co., Ltd." },
    { "08D3h": "SVI Public Company Limited " },
    { "08D4h": "Sensa-Lite Ltd." },
    { "08D5h": "Sense Effects" },
    { "08D6h": "Guangzhou Precision Vision Intelligent Equipment Co, Ltd" },
    { "08D7h": "PatternAgents, LLC" },
    { "08D8h": "W.A. Benjamin Electric Co." },
    { "08D9h": "STILED" },
    { "08DAh": "PLC Intelligent Technology (Shanghai) Co., Ltd." },
    { "08DDh": "Matthew Tong" },
    { "08DFh": "DetaiLED Solutions" },
    { "08E0h": "Red Arrow Controls" },
    { "08E1h": "Shenzhen CLT Electronics Co.,LTD " },
    { "08E2h": "Particle Studio Ltd." },
    { "08E3h": "Guangzhou JinZhiHui Electronic Technology Co.,Ltd." },
    { "08E4h": "LMP Lichttechnik Vertriebsgesellschaft GmbH & Co KG" },
    { "08E6h": "Shenzhen VisionMax Technology Co., Ltd" },
    { "08E7h": "3A Guangzhou Electronics Co., Ltd" },
    { "08E8h": "North Engineering" },
    { "08EAh": "Changchun Cedar Electronic Technology Co.,Ltd." },
    { "08EBh": "Guangzhou Lixin Lighting Co., Ltd." },
    { "08ECh": "Marvin Nadrowski" },
    { "08EDh": "ShowLED" },
    { "08EEh": "Spacelights" },
    { "08EFh": "Guangzhou RuiYang lighting technology co. LTD." },
    { "08F0h": "Guang Dong LMJ Lighting Co., Ltd" },
    { "08F1h": "SanDevices, LLC" },
    { "08F2h": "Virtualny Agronom Ltd." },
    { "08F3h": "Outdoor Lasers Ltd." },
    { "08F4h": "MC Electronic Technology(GZ) Co., Ltd." },
    { "08F5h": "Fufeng lighting" },
    { "08F6h": "Eulum Design, LLC" },
    { "08F7h": "Neotek Lighting" },
    { "08F8h": "Liberal Logic Inc." },
    { "08F9h": "ACS - Ackerman Computer Sciences" },
    { "08FAh": "Phaton Lighting Co., Ltd." },
    { "08FBh": "RPA Electronic Solutions Inc." },
    { "08FCh": "Lights By Brian" },
    { "08FDh": "Koto Electric Co., Ltd." },
    { "08FEh": "Zhuhai Shengchang Electronics Co., Ltd." },
    { "0900h": "nox multimedia Gmbh" },
    { "0901h": "GermTec GmbH & Co. KG" },
    { "0902h": "DongGuan Betterway Lighting Co.,Ltd" },
    { "0903h": "Shenzhen INFiLED Electronics, Ltd." },
    { "0904h": "Bigbear Co., Ltd." },
    { "0905h": "Locimation Pty Ltd" },
    { "0906h": "Crystal Technica Limited" },
    { "0907h": "Shenzhen GCL Electronics Co., Ltd " },
    { "0908h": "Guangzhou DeLong Stage Equipment Co., Ltd." },
    { "0909h": "Beijing Starlight Electronics Co., Ltd." },
    { "090Ah": "Jiangmen Seekway Technology Limited" },
    { "090Bh": "StarLighting" },
    { "090Ch": "GRE Alpha" },
    { "090Eh": "Sichuan esRadio Technology Co., Ltd" },
    { "090Fh": "Shenzhen Dingli Display Technology Co., Ltd" },
    { "0910h": "Shenzhen Tecnon EXCO-Vision Technology Co., Ltd." },
    { "0911h": "Guangzhou Aceda Professional Lighting Co., Ltd." },
    { "0912h": "ags - Wissenschaftliche Arbeitsgemeinschaft fur Studio- und Senderfragen" },
    { "0913h": "Guangzhou ECK Light Equipment Company Limited" },
    { "0914h": "Xenio" },
    { "0915h": "Guangzhou Chuangfeng Photoelectric Equipment Co., Ltd." },
    { "0916h": "ACTOR-MATE CO., LTD." },
    { "0917h": "Gavtronics" },
    { "0918h": "David O Smith Design" },
    { "0919h": "Foshan Leiyuan Photoelectric Co., LTD" },
    { "091Ah": "Celex LED Technology Ltd." },
    { "091Bh": "Krislite Pte. Ltd." },
    { "091Dh": "TouchPlate Technologies Inc." },
    { "091Eh": "Vanilla Internet Ltd" },
    { "091Fh": "Yaham Recience Technology Co,. ltd." },
    { "0920h": "Vexica Technology Limited" },
    { "0921h": "Guangzhou mengyi stage lighting equipment co., LTD." },
    { "0922h": "von Gaisberg Engineering" },
    { "0923h": "Hangzhou Roleds Lighting System Co., Ltd." },
    { "0925h": "Guangzhou Aiweidy Lighting Acoustics Equipment Co.,Ltd." },
    { "0926h": "Elumeros Lighting Limited " },
    { "0927h": "Guangzhou Mingying Electronic Technology Co., Ltd." },
    { "0928h": "Chaostreff Backnang e.V. " },
    { "0929h": "UPlight stage equipment(GZ) CO., Ltd." },
    { "092Bh": "Guangzhou Lightful Stage Lighting&Sound Equipment Co,.Ltd." },
    { "092Ch": "Guangzhou Chaoran Computer Co., Ltd." },
    { "092Dh": "LG Electronics" },
    { "092Eh": "YouEasy (Dongguan) Electronics Technology Co.,Ltd" },
    { "092Fh": "Guangzhou Shinelight Stage Equipment Factory " },
    { "0930h": "jiaozuo shengguang film &equipment Co. Ltd" },
    { "0931h": "Cristal Controles" },
    { "0932h": "GUANGZHOU BORAY ELECTRON CO.,LTD" },
    { "0933h": "Beyond Lighting WLL" },
    { "0934h": "Zenopix Electronic Limited Company" },
    { "0935h": "Guangzhou Huadu District Richa Lighting Equipment Factory" },
    { "0936h": "AquaTronic" },
    { "0937h": "Huizhou Zhonghan Electronic Technology Co., Ltd" },
    { "0938h": "Guangzhou Vanray Lighting Equipment CO.,Ltd." },
    { "0939h": "Edelmann Electronics" },
    { "093Ah": "HDT impex s.r.o." },
    { "093Bh": "Guangzhou Hongmingwei Stage Lighting Co., Ltd." },
    { "093Dh": "Sichuan Hushan Electric Co. Ltd" },
    { "093Fh": "Guangzhou Julong Platform Lighting Equipment Factory" },
    { "0940h": "Shenzhen CreateLED Electronics Co., Ltd" },
    { "0941h": "Shenzen Zhuoyang Intelligent Technology Co., Ltd." },
    { "0942h": "Showjockey Technology Co., Ltd" },
    { "0943h": "Guangzhou Guangying Optoelectronics Co., Ltd" },
    { "0945h": "Guangzhou Lin Xiang Stage Lighting Equipment CO.,LTD" },
    { "0946h": "TBE Srl" },
    { "0947h": "Shenzhen MOSO Electronics Technology Co., Ltd" },
    { "0948h": "Wisconsin Lighting Lab, Inc. (WiLL)" },
    { "0949h": "Shenzhen Jiuzhou Optoelectronic Technology" },
    { "094Ah": "Funovation, Inc" },
    { "094Bh": "Invisua Lighting BV" },
    { "094Ch": "Shenzhen Xiezhen Electronics Co., Ltd." },
    { "094Dh": "Quantum Theory" },
    { "094Eh": "Myostat Motion Control" },
    { "0951h": "Guangzhou GTD Lighting Technology Co., Ltd " },
    { "0952h": "Guangzhou Sunway Entertainment Equipment Co., Ltd." },
    { "0953h": "Boumakers Techniek" },
    { "0954h": "Ledtop Visual Ltd." },
    { "0955h": "8lightspace limited" },
    { "0956h": "Expromo Europe A/S" },
    { "0957h": "White Light Ltd" },
    { "0958h": "Illum Technology LLC (previously Verde Designs, Inc.)" },
    { "0959h": "Urbs Lighting, LLC" },
    { "095Ah": "kLabs Research UK" },
    { "095Bh": "Wuhan Zhongtian Jiaye Mechanical and Electrical Engineering Co. LTD" },
    { "095Ch": "Thomas Neumann Licht und Tontechnik" },
    { "095Dh": "Silver Curve Ltd" },
    { "095Eh": "Hondel Lighting Limited" },
    { "095Fh": "Elaborated Networks Gmbh" },
    { "0960h": "Fineline Solutions Ltd." },
    { "0962h": "Finland Lighting Oy" },
    { "0963h": "Foshan Sololighting Technology Co., Ltd" },
    { "0964h": "Inventions Guité Inc." },
    { "0965h": "Fontana Fountains" },
    { "0967h": "Arcus Licht- und Praesentationstechnik Gmbh" },
    { "0968h": "Guangzhou Beyond Lighting Co., Limited. " },
    { "096Ch": "Guangzhou Nebula Stage Lighting Equipment Co., Ltd" },
    { "096Dh": "Guangzhou Xin Yilong Stage Lighting Equipment Co., Limited" },
    { "096Eh": "Calvitia Limited " },
    { "096Fh": "Shenzhen showho technolgy co.,ltd " },
    { "0970h": "Aurum Engineering Gmbh" },
    { "0971h": "Plura Europe Gmbh" },
    { "0972h": "Holochrom Gmbh" },
    { "0973h": "Guangzhou Eagle Wei Photoelectric Technology Co., Ltd." },
    { "0974h": "Marumo Electric Co., Ltd." },
    { "0975h": "KB Design" },
    { "0976h": "Axion Lighting LLC" },
    { "0977h": "Guangzhou HuaYong Intelligent Technology Co., Ltd." },
    { "0978h": "LE Veranstaltungstechnik" },
    { "097Ah": "Teamboyce Limited" },
    { "097Dh": "Brink Electronics" },
    { "097Eh": "Guangzhou Deyi Lighting Co., Ltd." },
    { "097Fh": "RaumZeitLabor e.V." },
    { "0980h": "Moog Animatics" },
    { "0981h": "Luxam, Ltd." },
    { "0982h": "AC Entertainment Products Ltd." },
    { "0983h": "S Squared Innovations Inc." },
    { "0984h": "Laserworld AG" },
    { "0986h": "ROE Visual Co. Ltd." },
    { "0987h": "mathertel.de" },
    { "0989h": "YeGrin Liteworks" },
    { "098Ah": "DongGuan JuYang Electric Co., Ltd" },
    { "098Bh": "Glow Motion Technologies, LLC." },
    { "098Ch": "Shenzhen Longrich Energy Sources Technology Co., Ltd. " },
    { "098Dh": "Batmink Ltd." },
    { "098Eh": "Ecosense Lighting Inc" },
    { "098Fh": "Digital Sputnik Lighting" },
    { "0990h": "Stagelight Holding" },
    { "0991h": "Guangdong Pomelo Photoelectric Equipment Co., Ltd" },
    { "0992h": "Guangzhou Fengyi Stage Lighting Equipment Co., Ltd." },
    { "0993h": "Shenzhen Trigger digital Technology Co., LTD" },
    { "0995h": "Rasha Professional " },
    { "0996h": "CCI Power Supplies, LLC" },
    { "0997h": "Star Iluminacao Computadorizada LTDA" },
    { "0999h": "Concept Smoke Systems Ltd." },
    { "099Ah": "Aixz International (S)" },
    { "099Bh": "Luminoscape Lighting Limited" },
    { "099Dh": "Frenexport SPA" },
    { "099Eh": "LLC Lighting Technologies production" },
    { "09A0h": "Rnet Lighting Technology Limited" },
    { "09A1h": "Veranstaltungstechnik König" },
    { "09A2h": "Fountain People" },
    { "09A3h": "Shenzhen Lightlink Display Technology Co., Ltd" },
    { "09A4h": "Brighter Lighting Sp. z.o.o." },
    { "09A5h": "Prolight Concepts Ltd." },
    { "09AAh": "Rushstage Show Lighting Limited" },
    { "09ADh": "Dongguan Ensure Electronic Technology Co., LTD" },
    { "09AEh": "Robert Juliat" },
    { "09AFh": "Autotech Co." },
    { "09B0h": "Luminii" },
    { "09B1h": "Shenzhen Lianxinke Microelectronics Co., Ltd" },
    { "09B2h": "Guangzhou Hedong Electronics Co., LTD" },
    { "09B3h": "Aquatique Show Int." },
    { "09B4h": "Brompton Technology Ltd." },
    { "09B5h": "XBlack Visual Products" },
    { "09B6h": "Second String Studios" },
    { "09B7h": "inCon-trol water systems" },
    { "09B8h": "Prolites S.A.L." },
    { "09BAh": "Supervoimed OU" },
    { "09BBh": "Guangzhou Yiyi Technology Co., Ltd." },
    { "09BDh": "Shenzhen Zhongbo Photoelectric Co., Ltd" },
    { "09BEh": "Arctos Showlasertechnik Gmbh" },
    { "09C0h": "Guangzhou Rainbow Lighting Equipment CO.,LTD" },
    { "09C1h": "Argetron Elektrik Elektronik Organizasyon Gida San. ve Dis Tic. Ltd. Sti." },
    { "09C3h": "Velleman nv" },
    { "09C4h": "Guangzhou XinHuang Industrial Co., Ltd." },
    { "09C6h": "Photon Manufacturing" },
    { "09C7h": "ShoCobra" },
    { "09C8h": "Crystal Fountains Inc." },
    { "09CCh": "Motomuto Aps" },
    { "09D0h": "Luminar Enterprises" },
    { "09D1h": "Environmental Lights" },
    { "09D2h": "Shenzhen Siwelo Technology Co., LTD" },
    { "09D3h": "WLPS Wodielite Production Services" },
    { "09D4h": "Guangzhou Yilaiming Photoelectric Technology Co., Ltd" },
    { "09D5h": "Shenzhen ImagineVision Technology Limited" },
    { "09D6h": "Mittomakers" },
    { "09D7h": "Unilumin Group" },
    { "09D8h": "Pioneer Lighting Solutions India Pvt Ltd" },
    { "09DCh": "Froggys Fog" },
    { "09DDh": "Planet Innovation Products Inc" },
    { "09DEh": "Matthias Bauch Software" },
    { "09E9h": "Starway" },
    { "09EEh": "Suzhou Pinzong Electronic Technology, CO.,Ltd" },
    { "09EFh": "Andrea Croce " },
    { "09F8h": "UberDisplays" },
    { "09FCh": "deskontrol electronics" },
    { "0A01h": "Star-Reach Corporation" },
    { "0AAAh": "AAA-LUX" },
    { "0D0Ch": "SmartDC Inc." },
    { "0D0Eh": "DMX Engineering LLC" },
    { "1112h": "Zhuhai Bincolor Electronic Technology Co., Ltd." },
    { "1113h": "SiliconCore Technology, Inc." },
    { "1200h": "Seekway Technology Limited" },
    { "1201h": "PRICOM Design" },
    { "1202h": "Ushio Lighting, Inc." },
    { "1203h": "Movecat Gmbh" },
    { "1204h": "ARES s.r.l. - Socio Unico" },
    { "1205h": "Carbon Lighting Limited" },
    { "1206h": "Hangel Technology Co., Ltd." },
    { "1207h": "BSK Networks GbR" },
    { "1208h": "Nuvolight GmbH & Co KG" },
    { "1209h": "Philippe Bergeron Lights" },
    { "120Ah": "Bulldog Lighting and Events, Inc." },
    { "120Bh": "Brilliant Stages Ltd." },
    { "120Ch": "Shanxi Tian Gong Sheng Optoelectronic Equipment Technology Co." },
    { "1211h": "Recrealab " },
    { "1212h": "HPL Light Company" },
    { "1221h": "SAGITTER-SDJ-Proel" },
    { "1222h": "SM International" },
    { "1234h": "ESTA" },
    { "12DAh": "Newlab S.r.l." },
    { "12E0h": "Luxlight Skandinavien AB" },
    { "12EAh": "Kolberg Percussion Gmbh" },
    { "12F4h": "Stage Services Ltd." },
    { "12FAh": "Hollywood Rentals LLC" },
    { "12FEh": "City Design S.p.A." },
    { "131Eh": "Blossom Communications Corp." },
    { "1337h": "Raven Systems Design, Inc." },
    { "134Dh": "VT-Control" },
    { "1370h": "Ingenieurbuero Stahlkopf" },
    { "13AEh": "Smartpark Creative Solutions" },
    { "1460h": "SEIKO Epson Corporation" },
    { "1464h": "HUMAL Elektroonika OU" },
    { "1490h": "Grid Show Systems Inc." },
    { "14A0h": "Intense Lighting, LLC" },
    { "14ACh": "Zaklad Elektroniczny AGAT s.c." },
    { "1501h": "Artixium France SAS" },
    { "1506h": "v2 Lighting Group, Inc." },
    { "1507h": "LC Handels Gmbh" },
    { "1508h": "TommyDMX" },
    { "150Ch": "ACASS SYSTEMS LLC" },
    { "152Ah": "SHOWTACLE Ltd." },
    { "154Eh": "Fire & Magic" },
    { "15A0h": "GuangZhou MCSWE Technologies, INC " },
    { "15A2h": "FEIMEX" },
    { "15D0h": "Music & Lights S.r.l." },
    { "161Ah": "techKnow Design Ltd." },
    { "1626h": "LEDsistem Teknolojileri Tic. Ltd. Sti." },
    { "1627h": "Dynamic Visual Solutions LLC" },
    { "162Ah": "Nerd's Meter" },
    { "1690h": "awaptec Gmbh" },
    { "16A0h": "Audio Effetti Srl" },
    { "16AEh": "Electrone Americas Ltd. Co." },
    { "16DCh": "Traxon Technologies Ltd. " },
    { "16E4h": "Aboutshow Color Light Co., LTD" },
    { "1701h": "ARTBOX" },
    { "170Eh": "Serva Transport Systems Gmbh" },
    { "170Fh": "Kezun Stage Lighting Equipment Co., Ltd." },
    { "174Eh": "Nordgas SNe-lightingsystem" },
    { "1750h": "Yuesheng International Limited" },
    { "1808h": "Guangzhou Jinye Electronic Technology Co., Ltd." },
    { "1809h": "Rotolight" },
    { "180Ah": "Guangdong Longjoin Optoelectronics Technology Co. Ltd." },
    { "180Bh": "Light stream" },
    { "1871h": "Smoke Factory Gmbh" },
    { "1872h": "Super-Can Industry Growing Co. Ltd." },
    { "1873h": "Zhongshan Wellmake Electronic Technology Co., Ltd." },
    { "1888h": "GUANZHOU KAVON STAGE EQUIPMENT CO., LTD." },
    { "18A6h": "Steadfast Technology" },
    { "1900h": "ADJ Products LLC" },
    { "1901h": "Zhongshan Hiline Electronics Co., Ltd." },
    { "1938h": "Solid State Luminaires" },
    { "1998h": "PLS Electronics Ltd." },
    { "19B9h": "Duralamp S.p.A." },
    { "19BAh": "Guangzhou Xinzhijie Photoelectric Co., Ltd." },
    { "19BBh": "Panalux Ltd." },
    { "19BCh": "Newtone AS" },
    { "19F8h": "CEZOS Spolka z ograniczona odpowiedzialnoscia, sp.k." },
    { "1A00h": "LIGEO Gmbh" },
    { "1A0Dh": "Cineo Lighting" },
    { "1A16h": "WADAK Gmbh" },
    { "1A1Ah": "ValDim Waterfountains Ltd." },
    { "1A3Dh": "Red Lighting s.r.l." },
    { "1AFAh": "TMB" },
    { "1BB1h": "PH Lightning AB" },
    { "1BC0h": "ALS Stanislaw Binkiewicz" },
    { "1BC6h": "Studio S Music City" },
    { "1C80h": "Vehtec Tecnologia Ltda" },
    { "1CABh": "LTT sp. z o.o." },
    { "1E42h": "SSE Gmbh" },
    { "1E8Dh": "Moda Light" },
    { "1ECFh": "Masiero s.r.l." },
    { "1ED8h": "Antari Lighting And Effects Ltd." },
    { "2009h": "Zboxes Intelligent Technology (Shanghai) Co., Ltd. " },
    { "200Ah": "Vault189 Pty. Ltd." },
    { "2011h": "Gantom Lighting & Controls" },
    { "207Fh": "Padura Elektronik Gmbh" },
    { "20A6h": "ALADIN Architekturlicht Gmbh" },
    { "20ABh": "IlluminaPi SAS" },
    { "20ADh": "AZ e-lite Pte Ltd" },
    { "20B6h": "Alkalite LED Technology Corp" },
    { "20B8h": "Electron SA" },
    { "20B9h": "ARRI -- Arnold & Richter Cine Technik GmbH & Co. Betriebs KG" },
    { "20BAh": "AusChristmasLighting" },
    { "20BBh": "Able Laser Tech Co., Ltd. " },
    { "20BCh": "Beijing Pargolite Technology Co., Ltd." },
    { "20BDh": "Foshan Yoline Lighting Equipment Co., Ltd." },
    { "20BEh": "Uranus Lighting Co., Ltd." },
    { "20BFh": "Guangzhou Taifeng Stage Lighting Audio Equipment Factory" },
    { "20C0h": "KappaStyle Productions." },
    { "20C1h": "BrightBeats, LLC" },
    { "20C2h": "Demilight" },
    { "20C3h": "PIXILAB Technologies AB" },
    { "2121h": "Brother,Brother & Sons Aps" },
    { "2122h": "BEGLEC NV" },
    { "2130h": "Bart van Stiphout Electronics & Software" },
    { "21A1h": "Culture Crew bvba" },
    { "21A4h": "CHAUVET Lighting" },
    { "21A9h": "CaptSystemes" },
    { "21B3h": "Coolon Pty Ltd" },
    { "21B4h": "CHROMLECh" },
    { "21B5h": "ChromaCove LLC" },
    { "2208h": "C.I.M.E.S. (Conception Installation Maintenance En Eclairage & Sonorisation)" },
    { "2216h": "D-Light Designs, LLC" },
    { "2222h": "D.E.F. Srl" },
    { "2224h": "DAS Integrator Pte Ltd" },
    { "2239h": "Dream Solutions Ltd." },
    { "22A0h": "EAS SYSTEMS" },
    { "22A6h": "Elation Lighting Inc." },
    { "22A9h": "Engineering Solutions Inc." },
    { "22AAh": "EUTRAC - Intelligent Lighting Gmbh" },
    { "22ABh": "EVC" },
    { "22B9h": "Etherlight" },
    { "2337h": "Focon Showtechnic" },
    { "2338h": "Humanlitech Co., Ltd. " },
    { "2339h": "Sky-Skan Europe GmbH " },
    { "233Ah": "4 Frames Lost UG" },
    { "23B2h": "Gekko Technology Ltd." },
    { "2421h": "HB-Laserkomponenten Gmbh" },
    { "242Ah": "Hungaroflash" },
    { "2432h": "Helvar Ltd" },
    { "2470h": "Hale Microsystems LLC" },
    { "24A3h": "Lighting Innovation Group AG" },
    { "24AAh": "IT Ihme" },
    { "2500h": "RATOC Systems, Inc." },
    { "2501h": "Xero Manufacturing Pty Limited" },
    { "2621h": "LEADER LIGHT s.r.o." },
    { "2622h": "LDDE Vertriebs Gmbh" },
    { "2623h": "Leonh Hardware Enterprise Inc." },
    { "2624h": "Lisys Fenyrendszer Zrt." },
    { "2626h": "LLT Lichttechnik GmbH&CO.KG" },
    { "2627h": "Guangzhou Megota Technology Co., Ltd." },
    { "2630h": "Laservision" },
    { "2632h": "Lehigh Electric Products" },
    { "2635h": "LjusDesign AB" },
    { "2636h": "Lumonic Limited" },
    { "2637h": "Loxone Electronics Gmbh" },
    { "263Ah": "Lumenec Pty. Ltd." },
    { "263Ch": "I-Pix Digital Light Ltd." },
    { "26A2h": "MEGATECHNICS Ltd." },
    { "26B4h": "Milford Instruments Ltd." },
    { "2724h": "Nila Inc." },
    { "2727h": "Lumikit" },
    { "2734h": "Nixer Ltd." },
    { "27A8h": "Callegenix LLC" },
    { "2821h": "Pioneer Corporation" },
    { "2826h": "Peter Maes Technology" },
    { "2827h  ": "Peternet Electronics BVBA " },
    { "2829h": "PR-Electronic" },
    { "2836h": "Planungsbuero" },
    { "28E1h": "MTC maintronic Gmbh" },
    { "2927h": "ROAL Electronics SpA" },
    { "297Eh": "Lifetime Music Academy" },
    { "2984h": "Getlux Ltd." },
    { "2999h": "ALL-DO INTERNATIONAL CO., LTD." },
    { "29A1h": "Sturdy Corporation" },
    { "29A9h": "SRS Light Design" },
    { "29AAh": "Steinigke Showtechnic Gmbh" },
    { "29B2h": "Selectron Bvba" },
    { "29B4h": "Showtec (Highlite International B.V.)" },
    { "29B7h": "Sundrax, LLC" },
    { "29B8h": "Spotlight s.r.l." },
    { "29BAh": "State Automation Pty Ltd." },
    { "29E8h": "Stroytsirk LLC" },
    { "2A25h": "Thorn Lighting Limited" },
    { "2A26h": "Toni Maroni Gmb" },
    { "2AABh": "Urban Visuals & Effects Ltd." },
    { "2B28h": "Visual Productions" },
    { "2B29h": "MaNima Technologies BV" },
    { "2BA2h": "WERPAX bvba" },
    { "2BA9h": "The White Rabbit Company, Inc." },
    { "2BB4h": "Williams Electronic Design Ltd." },
    { "2C1Ah": "DMX4ALL Gmbh" },
    { "2C2Ah": "XTBA" },
    { "2CE0h": "Lighting Services Inc." },
    { "2DC8h": "Stellascapes" },
    { "2DDDh": "Waylight" },
    { "2DDEh": "Luminlite Electronics Co., Ltd." },
    { "2DDFh": "Carpetlight Gmbh" },
    { "3000h": "PushingPixels" },
    { "3001h": "Elemental LED, Inc." },
    { "3002h": "Siberian Lighting" },
    { "3003h": "ChamSix" },
    { "3235h": "de koster Special Effects" },
    { "3331h": "DMG Lumiere" },
    { "3332h": "Teclumen s.r.l." },
    { "3333h": "NightStarry Electronics Co., LTD." },
    { "3388h": "Macostar International Ltd." },
    { "3434h": "Global Design Solutions, Ltd." },
    { "3533h": "Figure 53, LLC" },
    { "3534h": "Five4, LLC" },
    { "3535h": "Changsha Spark Technology Electronics Ltd." },
    { "3536h": "Cindy Professional Lighting Co., Ltd. " },
    { "3537h": "Novacorp Inc." },
    { "3538h": "Lightnet sp. z o. o." },
    { "361Dh": "Lumishore Ltd. UK" },
    { "3638h": "Lumenpulse Lighting Inc." },
    { "37D0h": "Boogy Brothers Showequipment" },
    { "37D7h": "Lichttechnik & Sonderbau" },
    { "37DDh": "Sehr gute Gmbh" },
    { "3800h": "OndeLight LTD" },
    { "3801h": "SFX Controllers Sweden AB" },
    { "3805h": "Yifeng Lighting Co., Ltd." },
    { "3806h": "ACME EFFECTS LTD." },
    { "3868h": "LanBolight Technology Co., LTD." },
    { "3888h": "Fly Dragon Lighting Equipment Co.,ltd" },
    { "388Ah": "Guangzhou Yajiang (Yagang - Silver Star) Photoelectric Equipment Ltd." },
    { "3A37h": "TheOlymp - Networking & InterNet Services" },
    { "3AFCh": "Black Tank Engineering" },
    { "3B10h": "NXP Semiconductors B.V." },
    { "3B88h": "Shenzhen Eastar Electronic Co., Ltd." },
    { "3D30h": "zactrack Lighting Technologies Gmbh" },
    { "400Dh": "Quasar Science LLC" },
    { "4051h": "SAN JACK ANALOG HOUSE CO., LTD." },
    { "4131h": "Altman Stage Lighting" },
    { "4141h": "AVAB America, Inc." },
    { "4142h": "Filmgear, Inc." },
    { "4143h": "AC Lasers" },
    { "4144h": "ADB - TTV Technologies nv" },
    { "4145h": "ADE ELETTRONICA srl " },
    { "4146h": "AUS FX" },
    { "4149h": "Anidea Engineering, Inc." },
    { "414Ch": "Artistic Licence Engineering Ltd." },
    { "414Dh": "Amptown Lichttechnik Gmbh" },
    { "414Eh": "Anytronics Ltd." },
    { "4150h": "Apogee Lighting" },
    { "4151h": "Aquarii, Inc." },
    { "4153h": "Audio Scene" },
    { "4154h": "Arnold Tang Productions" },
    { "4156h": "Audio Visual Devices P/L" },
    { "4164h": "Adelto Industries Ltd." },
    { "416Ch": "Alenco BV" },
    { "4172h": "ARNOLD LICHTTECHNIK" },
    { "4173h": "Astera LED Technology Gmbh" },
    { "4179h": "AYRTON" },
    { "4241h": "BECKHOFF Automation Gmbh" },
    { "4243h": "Bill Coghill Company : Bill Coghill Design" },
    { "4245h": "Bytecraft Entertainment Pty Ltd" },
    { "424Fh": "BOTEX" },
    { "4253h": "Barco" },
    { "42A2h": "Birket Engineering, Inc." },
    { "4321h": "Design Partners of Canada" },
    { "4344h": "CDCA Ltd." },
    { "4347h": "CAST Software" },
    { "4349h": "C.I.Tronics Lighting Designers Ltda" },
    { "434Bh": "Color Kinetics Inc." },
    { "434Ch": "Crealux GmbH & Co. KG" },
    { "434Dh": "Coemar Spa" },
    { "434Fh": "Cortex Design" },
    { "4350h": "CLAY PAKY S.p.A" },
    { "4353h": "Capricorn Software" },
    { "4354h": "City Theatrical, Inc." },
    { "4358h": "Connex Gmbh" },
    { "4369h": "Cinetix Medien u. Interface Gmbh" },
    { "436Fh": "CODEM MUSIC S.r.l." },
    { "4441h": "DIGITAL ART SYSTEM" },
    { "4442h": "ELETTROLAB S.r.l." },
    { "4443h": "Claudio Dal Cero Engineering" },
    { "4444h": "D.O.M. Datenverarbeitung Gmbh" },
    { "4445h": "Dezelectric Kft." },
    { "4446h": "Doug Fleenor Design, Inc." },
    { "4449h": "Durand Interstellar, Inc." },
    { "444Ch": "Dove Lighting Systems, Inc." },
    { "444Dh": "Digimedia Multimedia Lighting Solutions" },
    { "444Eh": "DALCNET SRL" },
    { "4450h": "DMXPROFI.EU GmbH i.G." },
    { "4453h": "Guangzhou Desheng Lighting Industrial Co., Ltd." },
    { "4456h": "Devantech Ltd." },
    { "4466h": "DF elettronica s.r.l." },
    { "4469h": "Diamante Lighting Srl" },
    { "446Ch": "Guangdong Delos Lighting Industrial Co.,Ltd." },
    { "4533h": "LEDdynamics, Inc." },
    { "453Ah": "E:cue Control Gmbh" },
    { "4541h": "Engineering Arts" },
    { "4543h": "EC Elettronica Srl" },
    { "4544h": "Electronics Diversified LLC" },
    { "4545h": "EastSun Technology Co. Ltd." },
    { "454Ch": "Ingenieurbuero fuer Nachrichtentechnik in der Studio und Veranstaltungstechnik" },
    { "454Dh": "ELM Video Technology, Inc." },
    { "454Eh": "ENTTEC Pty Ltd" },
    { "4552h": "EREA" },
    { "4553h": "ERAL srl" },
    { "4554h": "Entertainment Technology" },
    { "4563h": "Les Eclairages Lou Inc." },
    { "456Ch": "Element Labs Inc." },
    { "4631h": "OKEROAB AB" },
    { "464Ch": "Flashlight/Ampco Holding" },
    { "4653h": "IT & Eventtechnik Fabian Stumpf" },
    { "4656h": "Flexvisual" },
    { "4657h": "The Fountain Workshop Ltd." },
    { "4658h": "MAGIC FX B.V." },
    { "4678h": "Global Special Effects" },
    { "4744h": "Goddard Design Co." },
    { "4745h": "GPE srl" },
    { "4747h": "G&G LED Lighting" },
    { "474Ch": "G-LEC Europe Gmbh" },
    { "4750h": "DES" },
    { "4752h": "Greenlite" },
    { "4753h": "Guangzhou Haoyang Electronic Co., Ltd." },
    { "476Ch": "General Luminaire (Shanghai) Ltd." },
    { "4800h": "VOD VISUAL.CO. (UK) Ltd." },
    { "4801h": "Capture Visualisation AB" },
    { "4843h": "Horizon Control Inc." },
    { "4844h": "HxDx" },
    { "4845h": "Howard Eaton Lighting Ltd." },
    { "484Ch": "HBE Lighting Systems" },
    { "484Fh": "Hollywood Controls Inc." },
    { "4856h": "Enfis Ltd" },
    { "4881h": "Rena Electronica B.V." },
    { "4941h": "inoage Gmbh" },
    { "4942h": "IBEX UK Limited" },
    { "4944h": "Ingham Designs" },
    { "4945h": "Insta Elektro Gmbh" },
    { "4947h": "IGuzzini illuminazione spa" },
    { "4948h": "Ice House Productions" },
    { "494Ch": "I-Lum" },
    { "494Eh": "Interactive Technologies, Inc." },
    { "4950h": "Interesting Products, Inc." },
    { "4951h": "IQAir AG" },
    { "4952h": "Invisible Rival Incorporated" },
    { "4953h": "Integrated System Technologies Ltd." },
    { "4954h": "Integrated Theatre, Inc." },
    { "4973h": "Innovation Solutions Ltd." },
    { "4A31h": "Joshua 1 Systems Inc." },
    { "4A41h": "JANUS srl" },
    { "4A42h": "JB-lighting Gmbh" },
    { "4A48h": "James Harris" },
    { "4A4Ch": "Johnsson Lighting Technologies AB" },
    { "4A53h": "JSC 'MFG'" },
    { "4A54h": "James Thomas Engineering" },
    { "4A61h": "Jands Pty Ltd." },
    { "4ACCh": "RVL techniek" },
    { "4B00h": "Gabor Galyas Lighting" },
    { "4B42h": "KissBox" },
    { "4B43h": "TmTech Electronic Co.,Ltd." },
    { "4B46h": "Kino Flo, Inc." },
    { "4B4Ch": "KLH Electronics PLC" },
    { "4B4Dh": "KMX Inc." },
    { "4B55h": "kuwatec, Inc." },
    { "4C20h": "LAM32 srl" },
    { "4C41h": "LaserAnimation Sollinger Gmbh" },
    { "4C44h": "LVDIAN PHOTOELECTRIC SCIENCE TECHNOLOGY LIMITED" },
    { "4C45h": "Leviton Manufacturing Co., Inc." },
    { "4C47h": "LightGeist Ltd." },
    { "4C4Ch": "LUMINEX Lighting Control Equipment bvba" },
    { "4C4Dh": "Ultratec Special Effects" },
    { "4C50h": "LightProcessor Ltd" },
    { "4C52h": "High End Systems Inc." },
    { "4C53h": "Licht-, Steuer- und Schaltanlagenbau GmbH (LSS GmbH)" },
    { "4C54h": "Licht-Technik" },
    { "4C55h": "LumenRadio AB" },
    { "4C56h": "LEDValley Technologies Sdn Bhd" },
    { "4C57h": "LightWild LC" },
    { "4C58h": "Lex Products Corp." },
    { "4C59h": "Laser Technology Ltd." },
    { "4C5Ah": "LightMinded Industries, Inc." },
    { "4C5Ah": "Sumolight Gmbh" },
    { "4C5Bh": "LightLife, Gesellschaft fur audiovisuelle Erlebnisse mbh" },
    { "4C64h": "LED Team" },
    { "4C65h": "Legargeant and Associates" },
    { "4C69h": "LIGHTOLIER" },
    { "4C6Ch": "Lampo Lighting Designers" },
    { "4C73h": "LSC Lighting Systems (Aust) Pty. Ltd." },
    { "4CDCh": "acdc LED Ltd." },
    { "4CE5h": "LED Company s.r.o." },
    { "4D41h": "MA Lighting Technology Gmbh" },
    { "4D42h": "LAN Systems--Midibox project" },
    { "4D44h": "Les Generateurs de brouillard MDG Fog Generators Ltd." },
    { "4D4Ch": "Mode Lighting (UK) Ltd." },
    { "4D50h": "Martin Professional A/S" },
    { "4D54h": "medien technik cords" },
    { "4D56h": "Avolites Ltd." },
    { "4D58h": "MX design" },
    { "4D5Ah": "Covert Science Gmbh" },
    { "4D61h": "MARTINI S.p.A." },
    { "4D77h": "Mueller Elektronik" },
    { "4E41h": "Company NA" },
    { "4E4Ah": "NJD Electronics" },
    { "4E4Ch": "NOVALIGHT S.r.l." },
    { "4E57h": "AIM Northwest" },
    { "4E69h": "Niko" },
    { "4F41h": "Oase Gmbh" },
    { "4F43h": "Offstage Controls (formerly Obsidian Control)" },
    { "4F4Ch": "DDS Elettronica" },
    { "4F75h": "Outsight Pty Ltd." },
    { "5000h": "http://www.orangepi-dmx.org" },
    { "5001h": "Hua Yuan Ke Tai" },
    { "5002h": "Shanghai Shylon Optoelectronic Technology Co., Ltd." },
    { "5003h": "Futlight Optoelectronics Co.,Ltd." },
    { "5004h": "Shanghai Sansi Electronic Engineering Co.,Ltd" },
    { "5005h": "MEDIAM Ltd. (Modus brand)" },
    { "5006h": "ENEDO Power SpA" },
    { "5007h": "Alfalite" },
    { "5008h": "Chengdu Chengyu Electronic Technology Co., Ltd." },
    { "5009h": "Izzro Optoelectronics Technology Co., Ltd." },
    { "500Ah": "AU Optronics Corporation (AUO)" },
    { "500Bh": "WebKat Eletronic's" },
    { "500Ch": "L.E.C. Societe Lyonnaise D' Equipement Et De Controle" },
    { "5010h": "Shenzhen Viye Technology Co., Ltd." },
    { "5011h": "Guangzhou Skydance Co., Ltd." },
    { "5017h": "American Lighting" },
    { "5040h": "Guangzhou Color Imagination LED Lighting Ltd." },
    { "5041h": "Philips Entertainment Lighting Asia" },
    { "5043h": "Pathway Connectivity Inc." },
    { "504Ch": "Peperoni Lighting-Solutions" },
    { "504Dh": "Peter Meyer Project Management Adviser Gmbh" },
    { "504Eh": "Uni-Bright nv" },
    { "5050h": "Newton Engineering and Design Group LLC" },
    { "5051h": "PDQ Manufacturing, Inc" },
    { "5052h": "Production Resource Group" },
    { "5053h": "Philips Selecon" },
    { "5058h": "PXM s.c." },
    { "5062h": "LED, Inc." },
    { "5065h": "Peradise" },
    { "5066h": "Pfannenberg Gmbh" },
    { "5068h": "Philips Lighting BV" },
    { "5070h": "Show Light Oy" },
    { "5071h": "Raindrop-Media" },
    { "5072h": "ARRI Rental Deutschland Gmbh" },
    { "5075h": "Pulsar Light of Cambridge Ltd." },
    { "5099h": "Altec Di Gregorio Andrea" },
    { "5100h": "Luxibel" },
    { "5101h": "LBT Electronics Pvt. Ltd." },
    { "5102h": "INDATA d.o.o." },
    { "512Dh": "DJPOWER ELECTRONIC STAGE LIGHTING FIXTURE FACTORY (GUANGZHOU)" },
    { "5149h": "JAP Optoelectronic Ltd." },
    { "514Dh": "QMAXZ lighting" },
    { "5153h": "QuickSilver Controls, Inc." },
    { "5168h": "Shenzhen Sunricher Technology Co.,Ltd." },
    { "516Ch": "Quicklights" },
    { "51D7h": "Innovative Dimmers LLC (Ratpac dimmers)" },
    { "51D8h": "Amperor Electronics (Shenzhen) Co., Ltd." },
    { "5200h": "Shenzhen Aotian Technology Co. , Ltd. " },
    { "5201h": "Crestron Electronics, Inc." },
    { "5202h": "Shenzhen Lianjin Photoelectricity Co., Ltd." },
    { "5244h": "Revolution Display" },
    { "524Ch": "Radical Lighting Ltd." },
    { "524Dh": "RUIZ TECh" },
    { "524Eh": "RNC Systems Inc." },
    { "5250h": "RootPath Ltd." },
    { "5252h": "RoscoLab Ltd." },
    { "5253h": "Robe Show Lighting s.r.o." },
    { "5341h": "Stage Technologies Limited" },
    { "5342h": "Industrias Sola Basic S.A. de C.V." },
    { "5343h": "Ocean Thin Films Inc." },
    { "5344h": "Stardraw.com Ltd." },
    { "5345h": "Selador" },
    { "5346h": "Synthe FX, LLC" },
    { "5347h": "SGM Technology For Lighting SPA" },
    { "5348h": "Schreder" },
    { "5349h": "Soundsculpture Incorporated" },
    { "534Ah": "SAS Productions" },
    { "534Bh": "SK-Software" },
    { "534Ch": "SOUNDLIGHT" },
    { "534Eh": "Sand Network Systems" },
    { "5353h": "Sean Sill" },
    { "5354h": "Stagetronics Ltda" },
    { "5355h": "Lochmun Ltd." },
    { "5356h": "OOO SAMLIGHT" },
    { "5363h": "SpaceCannon vh" },
    { "5368h": "ShowCAD Control Systems Ltd." },
    { "536Ch": "StageLine Electronic" },
    { "5370h": "Chroma-Q" },
    { "5374h": "STG-Beikirch Industrieelektronik + Sicherheitstechnik GmbH & Co. KG" },
    { "5376h": "SV-wtu eU" },
    { "5377h": "SWISSON AG" },
    { "5379h": "Singularity (UK) Ltd." },
    { "53A8h": "Simon Tech" },
    { "5431h": "AUTOLUX Handels- und Produktionsgmbh" },
    { "5441h": "TecArt Lighting " },
    { "5444h": "Technographic Displays Ltd." },
    { "5445h": "TESI Elettronica srl" },
    { "544Ch": "Tempest Lighting Inc." },
    { "5453h": "TalentStorm Enterprises, Inc." },
    { "5454h": "TamaTech Labo Company Ltd," },
    { "5459h": "TDE-Lighttech B.V." },
    { "5550h": "UP-LUX Eletronica Ltda." },
    { "5555h": "Martin Sukale Medientechnik GbR" },
    { "55AAh": "Emilum Gmbh" },
    { "564Ch": "Vari-Lite, Inc." },
    { "5651h": "Vision Quest Lighting Inc." },
    { "5652h": "Megapixel Visual Reality" },
    { "5653h": "Viso Systems Aps" },
    { "5655h": "Shenzhen CAS VU Technologies Co., Ltd." },
    { "5744h": "W-DEV" },
    { "5746h": "Wildfire, Inc." },
    { "5747h": "Wenger / JR Clancy" },
    { "5753h": "Wireless Solution Sweden AB" },
    { "5754h": "LIGHTMAN (Interlite AB)" },
    { "5759h": "Wybron, Inc." },
    { "584Ch": "X-Laser" },
    { "584Dh": "Xtraordinary Musical Accolade Systems" },
    { "5858h": "Illuminance Technologies" },
    { "5865h": "XENON ARCHITECTURAL LIGHTING" },
    { "586Ch": "Eurolumen (Shanghai) Lighting Co., LTD" },
    { "586Dh": "www.doityourselfchristmas.com hobbyists" },
    { "5888h": "Plsao Optoelectronics Technology Co., Ltd." },
    { "5A53h": "Zingerli Show Engineering" },
    { "5C40h": "OXO" },
    { "5D00h": "L1 Inc." },
    { "5D01h": "MTS Medientechnik Gmbh" },
    { "5D02h": "Underwater Lights Limited" },
    { "5DACh": "Mediatec Group" },
    { "5E5Dh": "Multisenses Gmbh" },
    { "5E5Eh": "Converging Systems Inc." },
    { "6019h": "Artifice Industries Ltd." },
    { "6100h": "Krobox Sdn Bhd" },
    { "610Ah": "Visenge Pty. Ltd " },
    { "6123h": "CMYLight (S) Pte. Ltd." },
    { "6124h": "Fiilex" },
    { "614Ch": "Alektra AB" },
    { "6154h": "Advatek Lighting" },
    { "6164h": "AVID Labs" },
    { "616Ch": "Advanced Lighting Systems" },
    { "6200h": "LUCITAG Ltd. " },
    { "6201h": "NuDelta Digital, LLC" },
    { "6202h": "ESCO Sp. z o.o." },
    { "6203h": "Flektor " },
    { "6204h": "Shenzhen Absen Optoelectronic Co., Ltd" },
    { "6205h": "Zhuhai Ltech Technology Co., Ltd." },
    { "6206h": "Lighting Innovation Company, LLC" },
    { "6273h": "B&S Elektronische Geräte Gmbh" },
    { "6342h": "Mega Systems Inc." },
    { "6364h": "CDS advanced technology bv" },
    { "636Dh": "Cambridge Micro Engineering Limited" },
    { "641Ah": "Heliospectra AB" },
    { "644Ch": "bdL KG" },
    { "6461h": "Digilin Australia" },
    { "6464h": "Dangeross Design" },
    { "646Ch": "dilitronics Gmbh" },
    { "646Fh": "eldoLED BV" },
    { "6472h": "Ingenieurburo Steffens" },
    { "64B9h": "Finelite, Inc." },
    { "6542h": "eBrain Gmbh" },
    { "6543h": "LES-TV Ltd." },
    { "6547h": "euroGenie" },
    { "6553h": "EtherShow" },
    { "6555h": "Shantea Controls" },
    { "6565h": "Stratus Systems LLC" },
    { "656Ch": "ELC lighting" },
    { "6573h": "Environmental Lighting Solutions" },
    { "6574h": "Electronic Theatre Controls, Inc." },
    { "6576h": "eventa Aktiengesellschaft" },
    { "6600h": "WANTS Electronics Co. Ltd." },
    { "6644h": "Sunlab Technologies S.L." },
    { "666Dh": "MAD-Effects" },
    { "6673h": "Freescale Semiconductor U.K. Ltd." },
    { "6756h": "Lumisia Co., Ltd." },
    { "676Ch": "GLP German Light Products Gmbh" },
    { "67F0h": "Toshiba Lighting & Technology Corporation" },
    { "6816h": "ChamberPlus Co., Ltd" },
    { "6864h": "James Embedded Systems Engineering (JESE Ltd)" },
    { "6865h": "Hubbell Entertainment, Inc." },
    { "686Ch": "HERA LED" },
    { "694Ch": "iLight Technologies Inc" },
    { "6969h": "Better Way Lighting" },
    { "6974h": "Ittermann electronic Gmbh" },
    { "6A6Ah": "Roxx Gmbh" },
    { "6A6Bh": "JPK Systems Limited" },
    { "6B64h": "Key Delfin" },
    { "6B69h": "Magical Fountain SA de CV (Magic Fountain)" },
    { "6BEAh": "Remoticom BV" },
    { "6BEDh": "Planar Systems, Inc." },
    { "6BEEh": "Ephesus Lighting" },
    { "6BEFh": "Shenzhen Ifountain Technology Ltd." },
    { "6C6Dh": "Zumtobel Lighting Gmbh" },
    { "6C78h": "Claude Heintz Design" },
    { "6C92h": "Ambra Elettronica s.r.l." },
    { "6D61h": "MAL Effekt-Technik Gmbh" },
    { "6D62h": "MBN Gmbh" },
    { "6D63h": "Sein & Schein Gmbh" },
    { "6E00h": "LEDeco solution, s.r.o." },
    { "6F00h": "Guangzhou Huaying Stage Lighting Equipment Co. Ltd." },
    { "6F01h": "DAVAI!JPL" },
    { "6F02h": "hazebase (Uta Raabe e.K.)" },
    { "6FEAh": "Lumina Visual Productions" },
    { "6FEBh": "Insight Lighting" },
    { "6FECh": "Arc Lighting Co. Ltd." },
    { "6FEDh": "Explorentis" },
    { "6FEEh": "fos design sp. z o.o." },
    { "7000h": "Nippon Ceramic Co., Ltd." },
    { "700Ah": "Guangzhou Leemc Lighting Tech., Co., Ltd." },
    { "700Bh": "Vice Lighting DWC LLC" },
    { "7068h": "Pharos Architectural Controls" },
    { "7070h": "SBT Gmbh" },
    { "7072h": "Pr-Lighting Ltd." },
    { "7078h": "PixelRange Inc." },
    { "70F0h": "Pangolin Laser Systems, Inc. " },
    { "7151h": "The Light Source, Inc." },
    { "7363h": "Sean Christopher FX" },
    { "7365h": "Ballantyne Strong Inc." },
    { "736Ch": "Strand Lighting Ltd." },
    { "7400h": "Danalux" },
    { "7401h": "Harvatek Corporation" },
    { "7402h": "Chris Kallas" },
    { "7403h": "Yenrich Technology Corporation" },
    { "7764h": "WET" },
    { "7765h": "MKT engineering GmbH & Co. KG" },
    { "7777h": "DVT Light" },
    { "7788h": "DigitaLicht AG" },
    { "780Eh": "Mole-Richardson Co." },
    { "783Ah": "Audiolux Devices LLC" },
    { "786Ch": "XLN-t bvba" },
    { "7888h": "Tontron Photoelectric Co., Limited" },
    { "78B4h": "LED Flex Limited" },
    { "7900h": "Leprecon / CAE, Inc." },
    { "79BCh": "DC Reactive" },
    { "7A70h": "Open Lighting" },
    { "7AA0h": "Anaren Inc." },
    { "7AAAh": "WEAD (Wagner Electronic and Design)" },
    { "7AABh": "Hyundai Fomex Co., Ltd." },
    { "7B1Bh": "DimLight Ltd." },
    { "7D00h": "expanseElectronics" },
    { "7D61h": "HMB|TEC Gmbh" },
    { "7DE7h": "Guangzhou ILightings Equipment Co., Ltd." },
    { "7DE8h": "Shenzhen LAMP Technology Co., Ltd." },
    { "7DEAh": "RobLight A/S" },
    { "7DEBh": "Krypton" },
    { "7DEEh": "zencontrol Pty Ltd" },
    { "7EE7h": "Arthur Digital Solutions Kft" },
    { "7EE8h": "Guangzhou Yingfeng Lighting Equipment Co., Ltd." },
    { "7EE9h": "Technology Kitchen" },
    { "7EEAh": "Cartwright Engineering " },
    { "7EEBh": "mylaserpage" },
    { "7EECh": "SHENZHEN LP Display" },
    { "7EEDh": "Look Solutions GmbH & Co. KG" },
    { "7EEEh": "General Lighting Electronic Co., Ltd." },
    { "7EEFh": "Huizhou Mounteck Technology Co., Ltd." },
    { "7FF0h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF1h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF2h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF3h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF4h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF5h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF6h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF7h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF8h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FF9h": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFAh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFBh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFCh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFDh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFEh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "7FFFh": "RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY" },
    { "FFFFh": "ESTA" }
];